### PR TITLE
Can u pwease merge my pwull wequest senpai?? UwU

### PR DESCRIPTION
**Pull request by BunnyCinnamon**
Hii~~ uwu **puts on cat ears**
I fixie wixied the twaco lang for my twaco fwiends!!  owo nyaa~~
repwaced all lowcawisation wiff a mow kawaii ~~ sugoii ne ~~ desu twaco lang that make mincrweft go sooper swuuper gud~! (づ｡◕‿‿◕｡)づ

can u pwease merge so mew twaco fwiends can _twerk_ with mew?!! OWO **licks you**

### CODE REVIEW

**Comment by ChloeDawn** [comment]
uwu

**Comment by antoinegag** [comment]
UwU

**Comment by blu0191** [comment]
UwU

**Comment by BunnyCinnamon** [comment]
UwU

**Comment by UpcraftLP** [comment]
OwO

**Pull request merged**
